### PR TITLE
Create Simple calculator in python

### PR DESCRIPTION
**Pull request by Hacktoberfest2**
Please merge this with approval commented as hactoberfest-accepted
As per the ne update from hacktober fest 2020

### CODE REVIEW

**Review by bigyanic — APPROVED** [review]

**Comment by Hacktoberfest2** [comment]
Please approve with hactoberfest-accepted
As per new update from hacktober fest

**Comment by Hacktoberfest2** [comment]
Otherwise it will not be considered

**Comment by Hacktoberfest2** [comment]
Please label with hacktoberfest-accepted

**Comment by Hacktoberfest2** [comment]
Please approve with label
 hacktoberfest-accepted

As per new update from hacktober fest
It is available at right side of screen

**Pull request merged**
